spring:
  application:
    name: app  # Имя приложения

  profiles:
    active: dev  # Используйте 'prod' для продакшен окружения через переменные окружения

# Конфигурация для профиля "dev" (H2 Database)
---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:h2:mem:devdb
    driver-class-name: org.h2.Driver
    username: sa
    password:  # Оставьте пустым для H2
    schema: classpath:db/schema.sql
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    open-in-view: false  # Отключить open-in-view
  sentry:
    dsn: ${SENTRY_DSN_DEV}  # Переменная окружения для dev профиля

# Конфигурация для профиля "prod" (PostgreSQL)
---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:postgresql://dpg-csck1dij1k6c739buutg-a.frankfurt-postgres.render.com:5432/dbname_w2y3
    driver-class-name: org.postgresql.Driver
    username: dbname_w2y3_user
    password: YWXdq9IHOpaAK7SjA0TF7JgmZNnabXbD
  jpa:
    hibernate:
      ddl-auto: update  # Или "validate", если вы не хотите автоматически изменять схему
    show-sql: true
    open-in-view: false  # Отключить open-in-view
  sentry:
    dsn: ${SENTRY_DSN_PROD}  # Переменная окружения для prod профиля

logging:
  level:
    root: DEBUG
    org.springframework.web: DEBUG
    org.hibernate: DEBUG
